var title = "Figure 6: Method of travel to work, by region";
var subtitle = "England and Wales, 2011";
var units = "%";
var yAxisTitle = "%";

var data = [];



var myChart;
$(document).ready(function(){
  



    // Prepare demo data
     data = [
{'name':'ENGLAND AND WALES','value':27.9},
{'name':'ENGLAND','value':27.7},
{'name':'WALES','value':30.8},
{'name':'NORTH EAST','value':35.5},
{'name':'County Durham','value':33.7},
{'name':'Darlington','value':38.2},
{'name':'Hartlepool','value':36.3},
{'name':'Middlesbrough','value':52.0},
{'name':'Northumberland','value':28.4},
{'name':'Redcar and Cleveland','value':35.4},
{'name':'Stockton-on-Tees','value':40.0},
{'name':'Tyne and Wear (Met county)','value':34.9},
{'name':'Gateshead','value':30.2},
{'name':'Newcastle upon Tyne','value':33.1},
{'name':'North Tyneside','value':33.7},
{'name':'South Tyneside','value':31.1},
{'name':'Sunderland','value':43.1},
{'name':'NORTH WEST','value':31.6},
{'name':'Blackburn with Darwen','value':33.2},
{'name':'Blackpool','value':42.9},
{'name':'Cheshire East','value':23.8},
{'name':'Cheshire West and Chester','value':28.5},
{'name':'Halton','value':40.4},
{'name':'Warrington','value':24.8},
{'name':'Cumbria','value':25.5},
{'name':'Allerdale','value':23.6},
{'name':'Barrow-in-Furness','value':32.4},
{'name':'Carlisle','value':25.7},
{'name':'Copeland','value':37.6},
{'name':'Eden','value':19.3},
{'name':'South Lakeland','value':16.9},
{'name':'Greater Manchester (Met county)','value':33.3},
{'name':'Bolton','value':30.3},
{'name':'Bury','value':32.6},
{'name':'Manchester','value':45.0},
{'name':'Oldham','value':33.1},
{'name':'Rochdale','value':35.0},
{'name':'Salford','value':37.9},
{'name':'Stockport','value':26.8},
{'name':'Tameside','value':32.7},
{'name':'Trafford','value':20.2},
{'name':'Wigan','value':32.0},
{'name':'Lancashire','value':28.7},
{'name':'Burnley','value':50.1},
{'name':'Chorley','value':29.5},
{'name':'Fylde','value':26.9},
{'name':'Hyndburn','value':38.5},
{'name':'Lancaster','value':27.0},
{'name':'Pendle','value':23.0},
{'name':'Preston','value':26.3},
{'name':'Ribble Valley','value':23.4},
{'name':'Rossendale','value':28.7},
{'name':'South Ribble','value':28.7},
{'name':'West Lancashire','value':20.4},
{'name':'Wyre','value':25.7},
{'name':'Merseyside (Met county)','value':34.4},
{'name':'Knowsley','value':39.3},
{'name':'Liverpool','value':35.7},
{'name':'Sefton','value':28.0},
{'name':'St Helens','value':38.1},
{'name':'Wirral','value':33.5},
{'name':'YORKSHIRE AND THE HUMBER','value':31.7},
{'name':'East Riding of Yorkshire','value':21.2},
{'name':'Kingston upon Hull‚ City of','value':39.3},
{'name':'North East Lincolnshire','value':41.5},
{'name':'North Lincolnshire','value':36.1},
{'name':'York','value':23.0},
{'name':'North Yorkshire','value':21.4},
{'name':'Craven','value':24.2},
{'name':'Hambleton','value':19.3},
{'name':'Harrogate','value':16.2},
{'name':'Richmondshire','value':27.4},
{'name':'Ryedale','value':12.8},
{'name':'Scarborough','value':28.7},
{'name':'Selby','value':25.3},
{'name':'South Yorkshire (Met county)','value':34.1},
{'name':'Barnsley','value':41.3},
{'name':'Doncaster','value':38.2},
{'name':'Rotherham','value':30.0},
{'name':'Sheffield','value':30.3},
{'name':'West Yorkshire (Met county)','value':33.3},
{'name':'Bradford','value':30.2},
{'name':'Calderdale','value':34.0},
{'name':'Kirklees','value':30.1},
{'name':'Leeds','value':37.5},
{'name':'Wakefield','value':33.7},
{'name':'EAST MIDLANDS','value':28.3},
{'name':'Derby','value':33.5},
{'name':'Leicester','value':32.9},
{'name':'Nottingham','value':37.7},
{'name':'Rutland','value':18.8},
{'name':'Derbyshire','value':22.3},
{'name':'Amber Valley','value':19.1},
{'name':'Bolsover','value':22.6},
{'name':'Chesterfield','value':29.9},
{'name':'Derbyshire Dales','value':9.2},
{'name':'Erewash','value':25.4},
{'name':'High Peak','value':22.5},
{'name':'North East Derbyshire','value':22.4},
{'name':'South Derbyshire','value':24.2},
{'name':'Leicestershire','value':21.7},
{'name':'Blaby','value':16.1},
{'name':'Charnwood','value':23.4},
{'name':'Harborough','value':24.3},
{'name':'Hinckley and Bosworth','value':21.3},
{'name':'Melton','value':22.4},
{'name':'North West Leicestershire','value':26.6},
{'name':'Oadby and Wigston','value':15.1},
{'name':'Lincolnshire','value':30.5},
{'name':'Boston','value':34.5},
{'name':'East Lindsey','value':36.9},
{'name':'Lincoln','value':40.1},
{'name':'North Kesteven','value':25.6},
{'name':'South Holland','value':27.7},
{'name':'South Kesteven','value':28.1},
{'name':'West Lindsey','value':23.7},
{'name':'Northamptonshire','value':30.8},
{'name':'Corby','value':47.2},
{'name':'Daventry','value':26.4},
{'name':'East Northamptonshire','value':26.9},
{'name':'Kettering','value':30.4},
{'name':'Northampton','value':36.1},
{'name':'South Northamptonshire','value':12.1},
{'name':'Wellingborough','value':33.7},
{'name':'Nottinghamshire','value':29.4},
{'name':'Ashfield','value':37.1},
{'name':'Bassetlaw','value':25.8},
{'name':'Broxtowe','value':19.3},
{'name':'Gedling','value':27.8},
{'name':'Mansfield','value':41.3},
{'name':'Newark and Sherwood','value':34.5},
{'name':'Rushcliffe','value':18.8},
{'name':'WEST MIDLANDS','value':32.0},
{'name':'Herefordshire','value':24.7},
{'name':'Shropshire','value':24.3},
{'name':'Stoke-on-Trent','value':51.3},
{'name':'Telford and Wrekin','value':36.8},
{'name':'Staffordshire','value':28.9},
{'name':'Cannock Chase','value':31.6},
{'name':'East Staffordshire','value':24.5},
{'name':'Lichfield','value':33.5},
{'name':'Newcastle-under-Lyme','value':29.9},
{'name':'South Staffordshire','value':15.2},
{'name':'Stafford','value':26.1},
{'name':'Staffordshire Moorlands','value':32.1},
{'name':'Tamworth','value':44.0},
{'name':'Warwickshire','value':24.3},
{'name':'North Warwickshire','value':29.0},
{'name':'Nuneaton and Bedworth','value':38.4},
{'name':'Rugby','value':20.8},
{'name':'Stratford-on-Avon','value':16.2},
{'name':'Warwick','value':17.1},
{'name':'West Midlands (Met county)','value':34.6},
{'name':'Birmingham','value':30.0},
{'name':'Coventry','value':38.6},
{'name':'Dudley','value':34.6},
{'name':'Sandwell','value':38.5},
{'name':'Solihull','value':23.8},
{'name':'Walsall','value':46.9},
{'name':'Wolverhampton','value':42.2},
{'name':'Worcestershire','value':27.3},
{'name':'Bromsgrove','value':19.0},
{'name':'Malvern Hills','value':22.1},
{'name':'Redditch','value':34.5},
{'name':'Worcester','value':43.1},
{'name':'Wychavon','value':21.6},
{'name':'Wyre Forest','value':25.3},
{'name':'EAST','value':23.2},
{'name':'Bedford','value':28.9},
{'name':'Central Bedfordshire','value':26.7},
{'name':'Luton','value':29.3},
{'name':'Peterborough','value':36.0},
{'name':'Southend on Sea','value':30.4},
{'name':'Thurrock','value':30.5},
{'name':'Cambridgeshire','value':16.8},
{'name':'Cambridge','value':12.9},
{'name':'East Cambridgeshire','value':16.3},
{'name':'Fenland','value':29.0},
{'name':'Huntingdonshire','value':14.6},
{'name':'South Cambridgeshire','value':14.2},
{'name':'Essex','value':23.9},
{'name':'Basildon','value':34.9},
{'name':'Braintree','value':23.0},
{'name':'Brentwood','value':12.0},
{'name':'Castle Point','value':20.8},
{'name':'Chelmsford','value':19.4},
{'name':'Colchester','value':27.5},
{'name':'Epping Forest','value':21.7},
{'name':'Harlow','value':37.1},
{'name':'Maldon','value':16.6},
{'name':'Rochford','value':15.0},
{'name':'Tendring','value':32.4},
{'name':'Uttlesford','value':9.8},
{'name':'Hertfordshire','value':17.4},
{'name':'Broxbourne','value':20.8},
{'name':'Dacorum','value':13.0},
{'name':'East Hertfordshire','value':12.2},
{'name':'Hertsmere','value':15.7},
{'name':'North Hertfordshire','value':20.5},
{'name':'St Albans','value':14.6},
{'name':'Stevenage','value':31.0},
{'name':'Three Rivers','value':11.6},
{'name':'Watford','value':23.6},
{'name':'Welwyn Hatfield','value':18.3},
{'name':'Norfolk','value':23.9},
{'name':'Breckland','value':20.5},
{'name':'Broadland','value':10.9},
{'name':'Great Yarmouth','value':35.6},
{'name':'King\'s Lynn and West Norfolk','value':30.0},
{'name':'North Norfolk','value':16.6},
{'name':'Norwich','value':39.8},
{'name':'South Norfolk','value':16.7},
{'name':'Suffolk','value':24.8},
{'name':'Babergh','value':18.9},
{'name':'Forest Heath','value':22.1},
{'name':'Ipswich','value':38.9},
{'name':'Mid Suffolk','value':19.1},
{'name':'St Edmundsbury','value':23.9},
{'name':'Suffolk Coastal','value':13.1},
{'name':'Waveney','value':34.1},
{'name':'LONDON','value':25.9},
{'name':'INNER LONDON','value':28.5},
{'name':'Camden','value':18.1},
{'name':'Hackney and City of London','value':28.8},
{'name':'Hammersmith and Fulham','value':25.6},
{'name':'Haringey','value':33.1},
{'name':'Islington','value':30.1},
{'name':'Kensington and Chelsea','value':17.7},
{'name':'Lambeth','value':33.2},
{'name':'Lewisham','value':42.0},
{'name':'Newham','value':24.1},
{'name':'Southwark','value':31.8},
{'name':'Tower Hamlets','value':24.3},
{'name':'Wandsworth','value':25.5},
{'name':'Westminster','value':21.2},
{'name':'OUTER LONDON','value':24.5},
{'name':'Barking and Dagenham','value':35.4},
{'name':'Barnet','value':14.7},
{'name':'Bexley','value':25.8},
{'name':'Brent','value':19.6},
{'name':'Bromley','value':24.2},
{'name':'Croydon','value':28.6},
{'name':'Ealing','value':22.4},
{'name':'Enfield','value':26.4},
{'name':'Greenwich','value':34.7},
{'name':'Harrow','value':14.2},
{'name':'Havering','value':26.4},
{'name':'Hillingdon','value':27.7},
{'name':'Hounslow','value':30.4},
{'name':'Kingston upon Thames','value':20.0},
{'name':'Merton','value':25.5},
{'name':'Redbridge','value':16.2},
{'name':'Richmond upon Thames','value':19.9},
{'name':'Sutton','value':25.8},
{'name':'Waltham Forest','value':29.9},
{'name':'SOUTH EAST','value':23.2},
{'name':'Bracknell Forest','value':17.3},
{'name':'Brighton and Hove','value':29.1},
{'name':'Isle of Wight','value':33.6},
{'name':'Medway','value':33.6},
{'name':'Milton Keynes','value':25.5},
{'name':'Portsmouth','value':39.9},
{'name':'Reading','value':35.9},
{'name':'Slough','value':21.0},
{'name':'Southampton','value':34.3},
{'name':'West Berkshire','value':19.7},
{'name':'Windsor and Maidenhead','value':14.6},
{'name':'Wokingham','value':15.4},
{'name':'Buckinghamshire','value':17.3},
{'name':'Aylesbury Vale','value':19.2},
{'name':'Chiltern','value':13.5},
{'name':'South Bucks','value':16.5},
{'name':'Wycombe','value':17.9},
{'name':'East Sussex','value':25.0},
{'name':'Eastbourne','value':25.6},
{'name':'Hastings','value':49.9},
{'name':'Lewes','value':19.7},
{'name':'Rother','value':19.8},
{'name':'Wealden','value':15.7},
{'name':'Hampshire','value':21.1},
{'name':'Basingstoke and Deane','value':23.1},
{'name':'East Hampshire','value':18.5},
{'name':'Eastleigh','value':23.3},
{'name':'Fareham','value':16.0},
{'name':'Gosport','value':22.8},
{'name':'Hart','value':12.1},
{'name':'Havant','value':34.2},
{'name':'New Forest','value':17.1},
{'name':'Rushmoor','value':32.1},
{'name':'Test Valley','value':17.8},
{'name':'Winchester','value':15.4},
{'name':'Kent','value':25.9},
{'name':'Ashford','value':23.9},
{'name':'Canterbury','value':20.6},
{'name':'Dartford','value':32.4},
{'name':'Dover','value':31.6},
{'name':'Gravesham','value':29.7},
{'name':'Maidstone','value':19.2},
{'name':'Sevenoaks','value':16.6},
{'name':'Shepway','value':27.8},
{'name':'Swale','value':35.6},
{'name':'Thanet','value':36.1},
{'name':'Tonbridge and Malling','value':26.1},
{'name':'Tunbridge Wells','value':13.5},
{'name':'Oxfordshire','value':20.7},
{'name':'Cherwell','value':24.0},
{'name':'Oxford','value':26.4},
{'name':'South Oxfordshire','value':16.1},
{'name':'Vale of White Horse','value':13.6},
{'name':'West Oxfordshire','value':23.0},
{'name':'Surrey','value':18.0},
{'name':'Elmbridge','value':17.6},
{'name':'Epsom and Ewell','value':23.2},
{'name':'Guildford','value':15.2},
{'name':'Mole Valley','value':8.8},
{'name':'Reigate and Banstead','value':19.8},
{'name':'Runnymede','value':24.0},
{'name':'Spelthorne','value':34.2},
{'name':'Surrey Heath','value':19.4},
{'name':'Tandridge','value':17.4},
{'name':'Waverley','value':9.1},
{'name':'Woking','value':15.4},
{'name':'West Sussex','value':22.5},
{'name':'Adur','value':32.6},
{'name':'Arun','value':24.2},
{'name':'Chichester','value':24.8},
{'name':'Crawley','value':30.0},
{'name':'Horsham','value':13.3},
{'name':'Mid Sussex','value':14.9},
{'name':'Worthing','value':29.3},
{'name':'SOUTH WEST','value':24.8},
{'name':'Bath and North East Somerset','value':18.0},
{'name':'Bournemouth','value':26.6},
{'name':'Bristol‚ City of','value':28.5},
{'name':'Cornwall','value':26.1},
{'name':'North Somerset','value':17.5},
{'name':'Plymouth','value':39.5},
{'name':'Poole','value':22.7},
{'name':'South Gloucestershire','value':17.6},
{'name':'Swindon','value':27.8},
{'name':'Torbay','value':39.5},
{'name':'Wiltshire','value':21.5},
{'name':'Devon','value':27.4},
{'name':'East Devon','value':18.0},
{'name':'Exeter','value':32.7},
{'name':'Mid Devon','value':33.5},
{'name':'North Devon','value':25.4},
{'name':'South Hams','value':26.2},
{'name':'Teignbridge','value':35.4},
{'name':'Torridge','value':20.2},
{'name':'West Devon','value':28.2},
{'name':'Dorset','value':22.1},
{'name':'Christchurch','value':26.6},
{'name':'East Dorset','value':19.3},
{'name':'North Dorset','value':15.3},
{'name':'Purbeck','value':27.3},
{'name':'West Dorset','value':21.1},
{'name':'Weymouth and Portland','value':28.3},
{'name':'Gloucestershire','value':20.9},
{'name':'Cheltenham','value':15.7},
{'name':'Cotswold','value':14.4},
{'name':'Forest of Dean','value':16.8},
{'name':'Gloucester','value':34.8},
{'name':'Stroud','value':21.8},
{'name':'Tewkesbury','value':17.3},
{'name':'Somerset','value':24.4},
{'name':'Mendip','value':28.1},
{'name':'Sedgemoor','value':24.5},
{'name':'South Somerset','value':25.4},
{'name':'Taunton Deane','value':20.1},
{'name':'West Somerset','value':20.2},
{'name':'WALES','value':30.8},
{'name':'Isle of Anglesey','value':37.8},
{'name':'Gwynedd','value':32.5},
{'name':'Conwy','value':33.9},
{'name':'Denbighshire','value':33.0},
{'name':'Flintshire','value':29.9},
{'name':'Wrexham','value':37.1},
{'name':'Powys','value':19.1},
{'name':'Ceredigion','value':20.7},
{'name':'Pembrokeshire','value':28.6},
{'name':'Carmarthenshire','value':27.8},
{'name':'Swansea','value':26.7},
{'name':'Neath Port Talbot','value':32.9},
{'name':'Bridgend','value':37.4},
{'name':'The Vale of Glamorgan','value':28.4},
{'name':'Cardiff','value':35.0},
{'name':'Rhondda Cynon Taf','value':35.5},
{'name':'Merthyr Tydfil','value':31.9},
{'name':'Caerphilly','value':26.3},
{'name':'Blaenau Gwent','value':39.9},
{'name':'Torfaen','value':30.2},
{'name':'Monmouthshire','value':20.6},
{'name':'Newport','value':30.8},
    ];

    $.getJSON('../data/LAD_DEC_2011_EW_BGC_5PC_1DP.json', function (geojson) {
    //$.getJSON('../data/gb-all.js', function (geojson) {


var axisColors = ['#375d93', '#4574b8', '#6990c7', '#8eabd5','#b3c7e3','#d8e2f0'];
        // Initiate the chart
        $('#chart').highcharts('Map', {
          chart: {
                backgroundColor: ''
            },

            title : {
                text : 'Figure 6: Under 18 conception rates by local authority, 2012 in England and Wales'
            },

            mapNavigation: {
                enabled: true,
                buttonOptions: {
                    verticalAlign: 'bottom'
                }
            },


          colorAxis: {
              dataClasses: [{
                  from: 0,
                  to: 20,
                  color: axisColors[5]
              }, {
                  from: 20,
                  to: 25,
                  color: axisColors[4]
              }, {
                  from: 25,
                  to: 30,
                  color: axisColors[3]
              }, { 
                  from: 30,
                  to: 35,
                  color: axisColors[2]
              }, { 
                  from: 35,
                  to: 40,
                  color: axisColors[1]
              }, {
                  from: 40,
                  color: axisColors[0]
              }]
          },

            tooltip: {
                backgroundColor: '#e6e6e6',
                borderWidth: 0,
                shadow: false,
                useHTML: false,
                padding: 0,
                pointFormat: '{point.properties.LAD11NM}' + ' ::{point.code}: <b>{point.value}%</b>'
            },

            series : [{
                data : data,
                mapData: geojson,
                joinBy: ['LAD11NM', 'name'],
                name: 'Rate per 1000 women',
                borderColor: '#375D93',
                borderWidth: 0.2,
                states: {
                    hover: {
                        color: 'gold'
                    }
                },
                dataLabels: {
                    enabled: false,
                    format: '{point.properties.LAD11NM}'
                }
            }],
            credits:{
              enabled:false
            },
        });

    });


});



